export const GET_MORE_BOOKS = 'GET_MORE_BOOKS';

export const SET_SORT_CRITERIA = 'SET_SORT_CRITERIA';

export const MARK_BOOK_AS_CHECKED = 'MARK_BOOK_AS_CHECKED';

export const SET_BOOK_LOADING = 'SET_BOOK_LOADING';

